name: thgj_witch
description: A sample dartemis application
dependencies:
  dartemis:
    git:
      url: git://github.com/denniskaselow/dartemis.git
  gamedev_helpers:
    git:
      url: git://github.com/kayzgames/gamedev_helpers.git
      ref: games/damacreat/0.7.0
  vector_math: any


dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^0.4.4
  dartemis_builder:
    git: git://github.com/denniskaselow/dartemis_builder.git